### ISSUE TITLE
blank page/draft

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Vote#137]
**Scenario:**
Access a draft or click on "Create your adpool".
**Result obtained:**
Scrolling down, the page becomes blank.

[blank page draft.webm](https://github.com/SaTT-Wallet/Vote/assets/135624031/c68a05c7-7e0b-491b-a5a1-886151a18788)

**Comment by skanderKhabou** [comment]
fixed in [blank-page-issue-add-pool] branch
