### ISSUE TITLE
Adjust the size of the Althera network logo

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Vote#163]
Adjust the size of the Althera network logo relative to the other networks.

![arthera](https://github.com/SaTT-Wallet/Vote/assets/135624031/c316533c-5a8d-4e1e-8501-6f8a6f511376)

**Comment by skanderKhabou** [comment]
adjust logo and resize logo done !

**Comment by Marwa7894** [comment]
done
