### ISSUE TITLE
The deletion of social media accounts occurs in a predetermined order, regardless of the selected account's rank for deletion 

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Vote#167]
**Scenario:**

> Access the profile page.
> Associate more than one account within the same social network.
> Attempt to delete the second or third account.

**Result obtained:**

> The first account was always deleted.

[delete account1.webm](https://github.com/SaTT-Wallet/Vote/assets/135624031/4704fb23-5231-47d5-bd8b-efb38ffb8df9)

**Comment by skanderKhabou** [comment]
Done i fixed also the problem that occurs with linkedin accoutns this is related to the bug of the ticket 162

**Comment by Marwa7894** [comment]
fixed
