### ISSUE TITLE
menu items/bold

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Vote#36]
Menu items should not be bold only when selected.

![Sans titre7](https://github.com/SaTT-Wallet/Vote/assets/135624031/bddb11b5-64d7-4603-95af-1dd27f6790dc)

[menu item.webm](https://github.com/SaTT-Wallet/Vote/assets/135624031/8e204a26-dbcb-4822-aea0-97fec5e040d0)

**Comment by skanderKha** [comment]
I worked on this issue and fixed it in the menue and network fix branch the user should now see the selected section

**Comment by Marwa7894** [comment]
fixed
